# Generated by Django 5.2.3 on 2025-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
