# Generated by Django 5.2.3 on 2025-07-12 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
